/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/store/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description This method is used to retrieve the category hierarchy for an eBay user's store.<br><br><span class="tablenote"><strong>Note:</strong> Three levels of store categories are supported.</span> */
        get: operations["getStoreCategories"];
        put?: never;
        /** @description This method is used to add a single new custom category to a user's eBay store through an asynchronous request. A successful call returns the <b>getStoreTask</b> URI in the Location response header. Call <b>getStoreTask</b> (or <b>getStoreTasks</b>) method to retrieve the status of the add category operation.<br><br><span class="tablenote"><strong>Note:</strong> Three levels of store categories are supported.</span><br><br><div class="msgbox_important"><p class="msgbox_importantInDiv" data-mc-autonum="&lt;b&gt;&lt;span style=&quot;color: #dd1e31;&quot; class=&quot;mcFormatColor&quot;&gt;Important! &lt;/span&gt;&lt;/b&gt;"><span class="autonumber"><span><b><span style="color: #dd1e31;" class="mcFormatColor">Important!</span></b></span></span> If you initiate a category change, you cannot make additional category changes until the previous change request has completed. Use getStoreTask (or getStoreTasks) method to get latest status of your last request.</p></div> */
        post: operations["addStoreCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description This method is used to rename the single category of a user's eBay store through an asynchronous request. A successful call returns the <b>getStoreTask</b> URI in the Location response header. The user calls <b>getStoreTask</b> to retrieve the status of the rename category operation.<br><br><div class="msgbox_important"><p class="msgbox_importantInDiv" data-mc-autonum="&lt;b&gt;&lt;span style=&quot;color: #dd1e31;&quot; class=&quot;mcFormatColor&quot;&gt;Important! &lt;/span&gt;&lt;/b&gt;"><span class="autonumber"><span><b><span style="color: #dd1e31;" class="mcFormatColor">Important!</span></b></span></span> If you initiate a category change, you cannot make additional category changes until the previous change request has completed. Use getStoreTask (or getStoreTasks) method to get latest status of your last request.</p></div> */
        put: operations["renameStoreCategory"];
        post?: never;
        /** @description This method is used to delete one custom category of a user's eBay store through an asynchronous request. A successful call returns the <b>getStoreTask</b> URI in the Location response header. Call <b>getStoreTask</b> (or <b>getStoreTasks</b>) method to retrieve the status of the delete category operation.<br><br><div class="msgbox_important"><p class="msgbox_importantInDiv" data-mc-autonum="&lt;b&gt;&lt;span style=&quot;color: #dd1e31;&quot; class=&quot;mcFormatColor&quot;&gt;Important! &lt;/span&gt;&lt;/b&gt;"><span class="autonumber"><span><b><span style="color: #dd1e31;" class="mcFormatColor">Important!</span></b></span></span> If you initiate a category change, you cannot make additional category changes until the previous change request has completed. Use getStoreTask (or getStoreTasks) method to get latest status of your last request.</p></div> */
        delete: operations["deleteStoreCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description This method is used to retrieve information for an eBay user's store such as store name, store URL, and description. */
        get: operations["getStore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description This method retrieves the current status of a recent store operation. The unique identifier of the task is passed in as a path parameter. */
        get: operations["getStoreTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description This method retrieves the status of all async store tasks for a store. Every task is set as FAILED or COMPLETED once it's execution time reaches 24 hours. */
        get: operations["getStoreTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/categories/move_category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description This method is used to move an existing user's eBay store custom category through an asynchronous request. A successful call returns the <b>getStoreTask</b> URI in the Location response header. The user calls <b>getStoreTask</b> to retrieve the status of the move category operation.<br><br><div class="msgbox_important"><p class="msgbox_importantInDiv" data-mc-autonum="&lt;b&gt;&lt;span style=&quot;color: #dd1e31;&quot; class=&quot;mcFormatColor&quot;&gt;Important! &lt;/span&gt;&lt;/b&gt;"><span class="autonumber"><span><b><span style="color: #dd1e31;" class="mcFormatColor">Important!</span></b></span></span> If you initiate a category change, you cannot make additional category changes until the previous change request has completed. Use getStoreTask (or getStoreTasks) method to get latest status of your last request.</p></div> */
        post: operations["moveStoreCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The base request type of the <b>addStoreCategory</b> method. It is used to provide the name and location for the new category. */
        AddStoreCategoryRequestType: {
            /** @description The seller-specified name of the custom category.<br><br> <b>Max Length: </b>35 */
            categoryName?: string;
            /** @description This field is used to specify the parent category to which the new category belongs. To specify the new category as a top-level category, set the value of this field to -999, or just omit this field, as the default value is -999.<br>The <a href="/api-docs/sell/stores/resources/store/methods/getStoreCategories"><b>getStoreCategories</b></a> method can be used to retrieve store category IDs.<br><br><b>Default: ROOT</b> category ID<b>(-999)</b> if it's null. */
            destinationParentCategoryId?: string;
            /** @description If the store category specified as the <b>destinationParentCategoryId</b> is a leaf category with active listings, those listings are moved to the store category identified through this <b>listingDestinationCategoryId</b>. If this field is omitted, the new store category being added under the parent category inherits those listings.<br>The <a href="/api-docs/sell/stores/resources/store/methods/getStoreCategories"><b>getStoreCategories</b></a> method can be used to retrieve store category IDs.<br><br><b>Default:</b> Newly added category ID if it's null. */
            listingDestinationCategoryId?: string;
        };
        /** @description The base request type of the <b>deleteStoreCategory</b> method. It is used to provide a new category home for the listings that are currently in the store category to be deleted. */
        DeleteStoreCategoryRequestType: {
            /** @description This field is only needed if the category to be deleted or any of its children categories have one or more active listings. The operation will fail otherwise. All active listings in or under the category to be deleted will be moved to the store category specified in this field.<br>The <a href="/api-docs/sell/stores/resources/store/methods/getStoreCategories"><b>getStoreCategories</b></a> method can be used to retrieve store category IDs.<br><br> <b>Default: OTHER</b> category ID <b>(1)</b> if it's null. */
            listingDestinationCategoryId?: string;
        };
        /** @description This type defines the fields that can be returned in an error. */
        Error: {
            /** @description Identifies the type of erro. */
            category?: string;
            /** @description Name for the primary system where the error occurred. This is relevant for application errors. */
            domain?: string;
            /**
             * Format: int32
             * @description A unique number to identify the error.
             */
            errorId?: number;
            /** @description An array of request elements most closely associated to the error. */
            inputRefIds?: string[];
            /** @description A more detailed explanation of the error. */
            longMessage?: string;
            /** @description Information on how to correct the problem, in the end user's terms and language where applicable. */
            message?: string;
            /** @description An array of request elements most closely associated to the error. */
            outputRefIds?: string[];
            /** @description An array of name/value pairs that describe details the error condition. These are useful when multiple errors are returned. */
            parameters?: components["schemas"]["ErrorParameter"][];
            /** @description Further helps indicate which subsystem the error is coming from. System subcategories include: Initialization, Serialization, Security, Monitoring, Rate Limiting, etc. */
            subdomain?: string;
        };
        ErrorParameter: {
            /** @description The object of the error. */
            name?: string;
            /** @description The value of the object. */
            value?: string;
        };
        /** @description The base response type of the <b>getStoreCategories</b> method. This type provides the entire category hierarchy for the store. */
        GetStoreCategoriesResponseType: {
            /** @description An array of top-level categories defined for the eBay store. A childrenCategories array is used for second and third-level categories, if defined for the store. */
            storeCategories?: components["schemas"]["StoreCategoryType"][];
        };
        /** @description The base response type of the <b>getStore</b> method. It is used to describe a seller's eBay store, and includes the eBay Store name, the description of the store, the URL to the eBay Store. */
        GetStoreResponseType: {
            /** @description The seller-provided description of the eBay Store.<br><br> <b>Max length: </b>300 */
            description?: string;
            /** @description Indicates the time the store was last opened or reopened. */
            lastOpenedTime?: string;
            /** @description This container provides information about a Store logo. */
            logo?: components["schemas"]["StoreLogoType"];
            /** @description The name of the eBay Store. The name is shown at the top of the Store page.<br><br> <b>Max length: </b>35 */
            name?: string;
            /** @description The complete URL of the user's store. */
            url?: string;
            /** @description The relative URL path of the Store.<br><br> <b>Max length: </b>58 */
            urlPath?: string;
        };
        /** @description The base response type of the <b>getStoreTask</b> method. */
        GetStoreTaskResponseType: {
            /** @description This container provides detailed information about the status of the store task. */
            task?: components["schemas"]["StoreTaskType"];
        };
        /** @description The base response type of the <b>getStoreTasks</b> method. */
        GetStoreTasksResponseType: {
            /** @description This array provides detailed information about the status of one or more store tasks. */
            task?: components["schemas"]["StoreTaskType"][];
        };
        /** @description The base request type of the <b>moveStoreCategory</b> method. It is used to provide the name of the category to be moved and its new location. */
        MoveStoreCategoryRequestType: {
            /** @description The unique identifier of an eBay Store's custom category. eBay auto-generates this identifier when a seller establishes a custom store category. This category ID should not be confused with an eBay category ID. This is the category that is moved. */
            categoryId?: string;
            /** @description The new parent category of the category to be moved is specified in this field. If the category is being moved to level 1 category, set this value to <b>-999</b>. */
            destinationParentCategoryId?: string;
            /** @description This field is only needed if the category to be moved is a leaf category with listings, but a category that becomes a non-leaf category after the move. The listings of the category to be moved are moved to the category specified in this field. */
            listingDestinationCategoryId?: string;
        };
        /** @description The base request type of the <b>renameStoreCategory</b> method. It is used to rename a customized eBay Store category. */
        RenameStoreCategoryRequestType: {
            /** @description The seller-specified name of the custom category. This is the new name of the category specified through path parameter.<br><br> <b>Max Length: </b>35 */
            categoryName?: string;
        };
        /** @description This type is used to provide details about a customized eBay Store category. */
        StoreCategoryType: {
            /** @description Unique identifier of an eBay Store's custom category. eBay auto-generates this identifier when a seller establishes a custom store category. This category ID should not be confused with an eBay category ID. */
            categoryId?: string;
            /** @description The seller-specified name of the custom category. */
            categoryName?: string;
            /** @description This array is returned to show second and third-level store categories. eBay Stores support up to three category levels. */
            childrenCategories?: components["schemas"]["StoreCategoryType"][];
            /**
             * Format: int32
             * @description The level indicates the category level of the category tree.<br><span class="tablenote"><strong>Note:</strong> Three levels of store categories are supported. All categories belonging to the same parent should have the same level.</span>
             */
            level?: number;
            /**
             * Format: int32
             * @description The order in which the custom store category appears in the list of store categories when the eBay store is visited.
             */
            order?: number;
        };
        /** @description This type is used to provide url of the seller's store logo. */
        StoreLogoType: {
            /** @description The URL of the seller's store logo. */
            url?: string;
        };
        /** @description This type is used to provide details about the status of the Store Task. */
        StoreTaskType: {
            /** @description The unique identifier of an eBay Store task. */
            id?: string;
            /** @description This field provides a textual description on the status of the task, and could help user troubleshoot any issues if there is an issue with eBay creating the task. */
            message?: string;
            /** @description The enumeration value here indicates the processing status of the task. See the <b>StoreTaskStatusEnum</b> type for more information on supported status values. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/stores/types/api:StoreTaskStatusEnum'>eBay API documentation</a> */
            status?: string;
            /** @description The enumeration value indicates the task type. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/stores/types/api:StoreTaskTypeEnum'>eBay API documentation</a> */
            type?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStoreCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStoreCategoriesResponseType"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addStoreCategory: {
        parameters: {
            query?: never;
            header: {
                /** @description This header indicates the format of the request body provided by the client. Its value should be set to <b>application/json</b>. <br><br> For more information, refer to <a href="/api-docs/static/rest-request-components.html#HTTP" target="_blank ">HTTP request headers</a>. */
                "Content-Type": string;
            };
            path?: never;
            cookie?: never;
        };
        /** @description This call is used to add single new category of a user's eBay store. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AddStoreCategoryRequestType"];
            };
        };
        responses: {
            /** @description The request is accepted, user should get the location url in response to retrieve async task status. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    renameStoreCategory: {
        parameters: {
            query?: never;
            header: {
                /** @description This header indicates the format of the request body provided by the client. Its value should be set to <b>application/json</b>. <br><br> For more information, refer to <a href="/api-docs/static/rest-request-components.html#HTTP" target="_blank ">HTTP request headers</a>. */
                "Content-Type": string;
            };
            path: {
                /** @description The unique identifier of an eBay Store's custom category. eBay auto-generates this identifier when a seller establishes a custom store category. This category ID should not be confused with an eBay category ID. This is the category that is to be renamed. */
                category_id: string;
            };
            cookie?: never;
        };
        /** @description This call is used to rename the single category of a user's eBay store. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RenameStoreCategoryRequestType"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteStoreCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of an eBay Store's custom category. eBay auto-generates this identifier when a seller establishes a custom store category. This category ID should not be confused with an eBay category ID.<br> The <a href="/api-docs/sell/stores/resources/store/methods/getStoreCategories"><b>getStoreCategories</b></a> method can be used to retrieve store category IDs. */
                category_id: string;
            };
            cookie?: never;
        };
        /** @description This call is used to delete one category of a user's eBay store. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeleteStoreCategoryRequestType"];
            };
        };
        responses: {
            /** @description The request is accepted, user should get the location url in response to retrieve async task status. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStoreResponseType"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStoreTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of an eBay Store async task. A taskId value is returned in the response of other successful calls. (e.g.addStoreCategory, moveStoreCategory, deleteStoreCategory). */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStoreTaskResponseType"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStoreTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStoreTasksResponseType"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    moveStoreCategory: {
        parameters: {
            query?: never;
            header: {
                /** @description This header indicates the format of the request body provided by the client. Its value should be set to <b>application/json</b>. <br><br> For more information, refer to <a href="/api-docs/static/rest-request-components.html#HTTP" target="_blank ">HTTP request headers</a>. */
                "Content-Type": string;
            };
            path?: never;
            cookie?: never;
        };
        /** @description This method is used to move one category of a user's eBay store. This operation is an asynchronous request. A successful call returns the <b>getStoreTask</b> URI in the Location response header. The user calls <b>getStoreTask</b> to retrieve the status of the add category operation. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveStoreCategoryRequestType"];
            };
        };
        responses: {
            /** @description The request is accepted, user should get the location url in response to retrieve async task status. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
